global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node_services'
    metrics_path: '/metrics'
    static_configs:
      - targets:  # Lista de todos os serviços
        - 'user-service:8081'
        - 'chat-service:8082'
        - 'notification-service:8083'
        - 'gateway:8080'

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'notification-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['notification-service:8083']
