{
 "title": "Express App",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "service",
    "label": "Service",
    "query": "label_values(http_request_duration_seconds_count, service)"
   }
  ]
 },
 "panels": [
  {
   "title": "Response Codes per Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (status_code)(rate(http_request_duration_seconds_count{service=\"$service\"}[1m]))",
     "legendFormat": "HTTP {{status_code}}"
    }
   ]
  },
  {
   "title": "Average Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_sum{service=\"$service\"}[5m])) by (status_code) /\nsum(rate(http_request_duration_seconds_count{service=\"$service\"}[5m])) by (status_code)",
     "legendFormat": "HTTP {{status_code}}"
    }
   ]
  },
  {
   "title": "Requests Per Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (method, path)(rate(http_request_duration_seconds_count{service=\"$service\"}[1m]))",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_sum{service=\"$service\"}[5m])) by (method, path) /\nsum(rate(http_request_duration_seconds_count{service=\"$service\"}[5m])) by (method, path)",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "HTTP Status Codes (Success vs Errors)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count{service=\"$service\"}[1m])) by (status_code)",
     "legendFormat": "{{status_code}}"
    }
   ]
  }
 ]
}